#!/data/data/com.termux/files/usr/bin/bash
#
# Build the probe APK entirely on the phone, in Termux. No Android SDK, no PC.
#
#   pkg install openjdk-17 aapt apksigner dx curl
#   ./tools/termux-build.sh
#
# Produces build-termux/dex-refresh-probe.apk, signed with a local debug key.
#
# This deliberately avoids Gradle and AGP: both want an SDK with x86_64 native
# tools (aapt2) that will not run on an ARM phone. Instead it uses the plain
# javac -> dexer -> aapt -> apksigner pipeline, all of which Termux can provide.
#
# The framework jar it compiles against is org.robolectric:android-all, fetched
# from Maven Central. That single jar carries both the android.* classes javac
# needs and the resources.arsc aapt needs, so it stands in for android.jar.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="$ROOT/build-termux"
API=35
ANDROID_ALL_VERSION="15-robolectric-13954326"
ANDROID_ALL_URL="https://repo1.maven.org/maven2/org/robolectric/android-all/${ANDROID_ALL_VERSION}/android-all-${ANDROID_ALL_VERSION}.jar"
FRAMEWORK="${ANDROID_JAR:-$BUILD/android-all-${API}.jar}"
KEYSTORE="${DEXPROBE_KEYSTORE:-$HOME/.dexprobe-debug.keystore}"
KS_PASS="android"

say() { printf '\n== %s\n' "$*"; }
die() { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- preflight
say "Preflight"
missing=""
for tool in javac java aapt apksigner keytool; do
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
done
if [ -n "$missing" ]; then
    cat >&2 <<MSG
Missing required tools:$missing

Install them with:
    pkg install openjdk-17 aapt apksigner

If 'aapt' is not in your Termux repos, this route will not work and the
GitHub Actions build is the way to go - see docs/BUILDING.md.
MSG
    exit 1
fi

# A dexer: d8 is preferred, dx works too (the sources are kept free of
# lambdas/method references precisely so that plain dx can handle them).
DEXER=""
if command -v d8 >/dev/null 2>&1; then
    DEXER="d8"
elif command -v dx >/dev/null 2>&1; then
    DEXER="dx"
else
    die "No dexer found. Try: pkg install d8   (or: pkg install dx)"
fi
echo "dexer:      $DEXER"
echo "java:       $(java -version 2>&1 | head -1)"
echo "output:     $BUILD"

mkdir -p "$BUILD"

# ---------------------------------------------------------------- framework
if [ ! -f "$FRAMEWORK" ]; then
    say "Fetching framework jar (~186 MB, one time)"
    command -v curl >/dev/null 2>&1 || die "curl not found: pkg install curl"
    curl -fL --progress-bar -o "$FRAMEWORK.part" "$ANDROID_ALL_URL" \
        || die "download failed. Set ANDROID_JAR=/path/to/android.jar to use your own."
    mv "$FRAMEWORK.part" "$FRAMEWORK"
fi
echo "framework:  $FRAMEWORK"

# ------------------------------------------------------------- generated src
say "Generating BuildConfig"
VERSION_NAME="$(sed -n "s/.*versionName '\([^']*\)'.*/\1/p" "$ROOT/app/build.gradle" | head -1)"
VERSION_CODE="$(sed -n 's/.*versionCode \([0-9]*\).*/\1/p' "$ROOT/app/build.gradle" | head -1)"
GEN="$BUILD/gen/com/tiimoo/dexrefresh"
mkdir -p "$GEN"
cat > "$GEN/BuildConfig.java" <<EOF
package com.tiimoo.dexrefresh;

/** Generated by tools/termux-build.sh (AGP normally produces this). */
public final class BuildConfig {
    public static final String VERSION_NAME = "${VERSION_NAME:-0.1.0-probe}";
    public static final int VERSION_CODE = ${VERSION_CODE:-1};
}
EOF

# -------------------------------------------------------------- resources
say "Packaging resources"
rm -f "$BUILD/app.ap_"
aapt package -f \
    -M "$ROOT/app/src/main/AndroidManifest.xml" \
    -S "$ROOT/app/src/main/res" \
    -A "$ROOT/app/src/main/assets" \
    -I "$FRAMEWORK" \
    -F "$BUILD/app.ap_" \
    --min-sdk-version 31 \
    --target-sdk-version "$API"

# -------------------------------------------------------------- compile
say "Compiling"
rm -rf "$BUILD/classes"
mkdir -p "$BUILD/classes"
find "$ROOT/app/src/main/java" "$ROOT/xposed-stubs/src/main/java" "$BUILD/gen" \
    -name '*.java' > "$BUILD/sources.txt"
echo "$(wc -l < "$BUILD/sources.txt") source files"
javac -nowarn -encoding UTF-8 --release 8 \
    -cp "$FRAMEWORK" \
    -d "$BUILD/classes" \
    "@$BUILD/sources.txt"

# The Xposed stubs must not ship in the APK: LSPosed provides the real ones,
# and a packaged copy would shadow them at runtime.
say "Dropping compile-only Xposed stubs from the output"
rm -rf "$BUILD/classes/de"

# -------------------------------------------------------------- dex
say "Dexing"
rm -rf "$BUILD/dex"
mkdir -p "$BUILD/dex"
find "$BUILD/classes" -name '*.class' > "$BUILD/classes.txt"
if [ "$DEXER" = "d8" ]; then
    d8 --lib "$FRAMEWORK" --min-api 31 --output "$BUILD/dex" \
        @"$BUILD/classes.txt"
else
    dx --dex --min-sdk-version=31 --output="$BUILD/dex/classes.dex" "$BUILD/classes"
fi
[ -f "$BUILD/dex/classes.dex" ] || die "dexing produced no classes.dex"

# -------------------------------------------------------------- assemble
say "Assembling APK"
cp "$BUILD/app.ap_" "$BUILD/unsigned.apk"
( cd "$BUILD/dex" && aapt add -f "$BUILD/unsigned.apk" classes.dex >/dev/null )

if command -v zipalign >/dev/null 2>&1; then
    zipalign -f 4 "$BUILD/unsigned.apk" "$BUILD/aligned.apk"
    mv "$BUILD/aligned.apk" "$BUILD/unsigned.apk"
else
    echo "zipalign not installed; skipping alignment (the APK still installs)"
fi

# -------------------------------------------------------------- sign
if [ ! -f "$KEYSTORE" ]; then
    say "Creating a local debug keystore at $KEYSTORE"
    keytool -genkeypair -v \
        -keystore "$KEYSTORE" -storepass "$KS_PASS" -keypass "$KS_PASS" \
        -alias dexprobe -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=DeX Refresh Probe, OU=probe, O=local, C=US" >/dev/null
fi

say "Signing"
OUT="$BUILD/dex-refresh-probe.apk"
rm -f "$OUT"
apksigner sign --ks "$KEYSTORE" --ks-pass "pass:$KS_PASS" \
    --key-pass "pass:$KS_PASS" --ks-key-alias dexprobe \
    --out "$OUT" "$BUILD/unsigned.apk"
apksigner verify "$OUT" >/dev/null && echo "signature verified"

say "Done"
echo "APK: $OUT"
echo
echo "Install it, then: LSPosed -> Modules -> DeX Refresh Probe -> enable,"
echo "scope = System Framework only, reboot. See docs/USAGE.md."
